= Writing Internet-Drafts and RFCs in AsciiDoc
:source-highlighter: coderay
:icons: font

asciidoctor-rfc lets you write Internet-Drafts and RFCs in AsciiDoc, the
"http://asciidoctor.org/[asciidoctor]-way".

image:https://img.shields.io/gem/v/asciidoctor-rfc.svg["Gem Version", link="https://rubygems.org/gems/asciidoctor-rfc"]
image:https://img.shields.io/travis/riboseinc/asciidoctor-rfc/master.svg["Build Status", link="https://travis-ci.org/riboseinc/asciidoctor-rfc"]
image:https://codeclimate.com/github/riboseinc/asciidoctor-rfc/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/riboseinc/asciidoctor-rfc"]


== Introduction

The "xml2rfc" Vocabulary (hereinafter "`RFC XML`") is an XML-based language
used for writing
https://www.ietf.org/id-info/guidelines.html[Internet-Drafts]
and https://tools.ietf.org/html/rfc7322[RFCs (RFC7322)].

This gem allows you to author these types of documents in AsciiDoc, and outputs
RFC XML output in both v3 and v2 formats:

* v3 RFC XML (https://tools.ietf.org/html/rfc7991[RFC 7991])
* v2 RFC XML (https://tools.ietf.org/html/rfc7749[RFC 7749])

Its syntax is designed to be "`native-asciidoctor`":


== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem "asciidoctor-rfc"
----

And then execute:

[source,console]
----
$ bundle
----

Or install it yourself as:

[source,console]
----
$ gem install asciidoctor-rfc
----


== Quick Start

[source,asciidoc]
----
= My first document using asciidoctor-rfc
:doctype: internet-draft // or rfc
----


== Usage

Converting your AsciiDoc to RFC XML is a simple as running the
`./bin/asciidoctor-rfc` script using Ruby and passing our
AsciiDoc document file as the first argument.

[source,console]
----
$ ruby ./bin/asciidoctor-rfc3 draft-example-00.adoc  # RFC XML v3 output
$ ruby ./bin/asciidoctor-rfc2 draft-example-00.adoc  # RFC XML v2 output
## WIP: bundle exec asciidoctor -b asciidoctor-rfc3 draft-example-00.adoc # RFC XML v3 output
## WIP: bundle exec asciidoctor -b asciidoctor-rfc2 draft-example-00.adoc # RFC XML v2 output
----

When the script completes, you should see the RFC XML file `draft-example-00.xml` in the
same directory.


== Syntax

The converter follows native AsciiDoc/asciidoctor syntax as much as possible,
including built-in attributes and styles.

Extension commands are provided to fully support writing an Internet-Draft/RFC
in AsciiDoc/asciidoctor syntax.

=== Document Type: `rfc` or `internet-draft` (Mandatory)

Set the `doctype` attribute to set status of this document:

`:doctype: internet-draft` sets the document as an Internet-Draft:
* `rfc/front/seriesInfo@name` attribute will be set to `Internet-Draft` (in v3)
* `rfc/front/seriesInfo@value` will be set to the `:name:` attribute (in v3)
* `rfc@docName` will be set to the `:name:` attribute (in v2)

`:doctype: rfc` sets the document as an RFC:
* `rfc/front/seriesInfo@name` attribute will be set to `RFC` (in v3)
* `rfc/front/seriesInfo@value` will be set to the `:name:` attribute (in v3)
* `rfc@number` will be set to the `:name:` attribute (in v2)


=== Basic Document Attributes

`asciidoctor-rfc` allows setting the RFC XML document header using the following
document attributes. Complying with AsciiDoc syntax, no blank lines are
permitted between the title, listing of authors, and the document attributes.

Shared RFC XML v3/v2 syntax:

|===
| Markup              | RFC XML v2/v3 elements                            | Value Notes
| `= Document Title`  | rfc/front/title                                   |
| `:abbrev:`          | rfc/front/title@abbrev                            |
| `:ipr:`             | rfc@ipr                                           |
| `:ipr-extract:`     | rfc@iprExtract                                    |
| `:obsoletes:`       | rfc@obsoletes                                     | no need to insert list in brackets, as with MMark; assumed delimited by comma+space
| `:updates:`         | rfc@updates                                       | no need to insert list in brackets, as with MMark; assumed delimited by comma+space
| `:submission-type:` | rfc@submissionType                                | `IETF` (default), `independent`, `IAB`, and `IRTF`
| `:revdate:`         | front/date@day, front/date@month, front/date@year | For consistency with AsciiDoc, `:revdate:` is given as an ISO 8601 date; the converter breaks it down into day, month name and year
| `:area:`            | front/area                                        | Comma delimited
| `:workgroup:`       | front/workgroup                                   | Comma delimited
| `:keyword:`         | front/keyword                                     | Comma delimited
|===


=== Document Name / Number (Mandatory)

The `name` attribute sets the document's name. This should be a number if
the document is an RFC, and a name (in the form of `draft-ietf-somewg-someprotocol-07`)
if it is an Internet-Draft.

When `doctype` is set to:

* `internet-draft`: the value should be in the form `draft-ietf-somewg-someprotocol-07`.
** v3: the `front/seriesInfo@value` will be set to this value.
** v2: the `rfc@docName` will be set to this value.

* `rfc`: the value should be a number like `7991` as described https://tools.ietf.org/html/rfc7991#section-2.47.6[here]
** v3: the `front/seriesInfo@value` will be set to this value.
** v2: the `rfc@number` will be set to this value.


=== Document Status

Set the `status` attribute to set the current status of this document.

The following values are allowed: `standard`, `informational`, `experimental`, `bcp`, `fyi`, `full-standard`.

* In v3, this sets the first `front/seriesInfo` element with `@status` as one of those values to indicate this.
* In v2, this sets the `front@category` value to one of `std`, `bcp`, `info`, `exp`, `historic`.


=== Intended Series

// TODO: reworking of implementation syntax necessary.
// TODO: do we call this intended-status vs rfc-status?

Set the `intended-series` attribute to set the intended series of this
document.

The following values are allowed: `standard`, `informational`, `experimental`, `bcp`, `fyi`, `full-standard`.

When `doctype` is set to:

* `internet-draft`: this value can be one of `standard`, `full-standard`, `bcp`, `fyi`, `informational`,
  `experimental`, or `historic` to indicate the intended series once the document is published as an RFC.

** In v3, this sets a second `front/seriesInfo` element with `@status` as one of those values, and an empty `@name`, to indicate this.
** In v2, this sets the `front@category` value to one of `std`, `bcp`, `info`, `exp`, `historic`.

* `rfc`: this value can be one of `full-standard`, `bcp` or `fyi` to indicate the current status of this document.

** In v3, this sets a second `front/seriesInfo` element with `@status` as one of those values, and an empty `@name`, to indicate this.
** In v2, this sets the `front@category` value to one of `std`, `bcp`, `info`. (While in https://tools.ietf.org/html/rfc7749#appendix-A.1[v2], the values `exp`, `historic` are also possible for a RFC, our gem does not support it.)

////
TODO: figure this out with the right syntax
|`:intendedstatus:` | | front/seriesInfo@status | status of Internet Draft, once published as RFC. Given in `<seriesinfo>` element with an empty `name` attribute.
|`:rfcstatus: full-standard\|bcp\|fyi _number_` | | front/seriesInfo@status, front/seriesInfo@value = number | Given in `<seriesinfo>` element with empty `name` attribute
|`:rfcstatus: info\|exp\|historic` | | front/seriesInfo@status | Given in `<seriesinfo>` element with empty `name` attribute
////


=== Document Submission Type / Stream

Set document submission type via the `submission-type` document attribute.

The following values are allowed: `IETF` (default), `independent`, `IAB`, and `IRTF`.

* In v3, the `rfc@submissionType` and `rfc/front/seriesInfo@stream` attributes are set to this value.
* In v2, the `rfc@submissionType` is set to this value

// TODO: Doesn't seem that v3's `stream` needs its own command.


=== Document Consensus

Set document consensus type via the `consensus` document attribute.

These values are accepted: `false`, `true`.

* In v3, this is the value set for the `rfc@consensus` attribute.
* In v2, this is the value set for the `rfc@consensus` attribute, but `false` is written as `no` and `true` is written as `yes`.


=== Document Language

Set the document language using the `xml-lang` document attribute.

By default this is `en`.

* In v3 and v2, this is the value set for the `rfc@xml:lang` attribute.

While v3 supports marking specific elements with their own `xml:lang` attribute, this is not yet supported by our gem.


=== Document Attributes for v3 only

These attributes are only supported for the v3 converter.

|===
| Markup | RFC XML v3 element
|`:index-include:` | rfc@indexInclude
|`:sort-refs:` | rfc@sortRefs
|`:sym-refs:` | rfc@symRefs
|`:toc-include:` | rfc@tocInclude
|`:no-rfc-bold-bcp14:` | Override default assumption that boldface uppercase BCP14 word is to be rendered with `bcp14` tag
|===

////
TODO: I don't think this is used?
|`:series-no:` | rfc@seriesNo | |
////


=== Author Attributes

In an Internet-Draft/RFC, detailed information of an author is necessary, which
is not supported by the normal AsciiDoc syntax.

You will need to provide the following information:

==== Multiple Author Names

// TODO: Note that an author could simply be an "Organization" without the names.
// https://tools.ietf.org/html/rfc7991#section-2.7

Just like a normal AsciiDoc, provide this (sample of 3 authors):

[source,asciidoc]
----
firstname middlename(s) lastname <email>; firstname middlename(s) lastname <email>; firstname middlename(s) lastname <email>
----

These will be mapped as follows:

|===
| Markup | RFC XML v3/v2 elements
| `firstname middlename(s) lastname` | `front/author@fullname`
| `lastname` | `front/author@surname`
| `email` | `front/author/address/email`
|===

==== Per Author Attributes

In `asciidoctor-rfc`, detailed author attributes are given as document
attributes.

As multiple authors can be specified, the document attribute to specify the
first author uses a name `:role`, and the second onwards `:role_2`, etc.

Shared RFC XML v3/v2 syntax:

|===
| Markup | RFC XML v2/v3 elements | Notes
|`:fullname{_i}:` | front/author@fullname |
|`:forename_initials{_i}:` | front/author@initials | distinct from AsciiDoc `:initials:` attribute, which includes surname
|`:lastname{_i}:` | front/author@surname |
|`:role{_i}:` | front/author@role |
|`:organization{_i}:` | front/author/organization |
|`:organization_abbrev{_i}:` | front/author/organization@abbrev |
|`:email{_i}:` | front/author/address/email |
|`:fax{_i}:` | front/author/address/facsimile |
|`:uri{_i}:` | front/author/address/uri |
|`:phone{_i}:` | front/author/address/phone |
|`:street{_i}:` | front/author/address/postal/street | multiple lines are concatenated with `"\ "`.
|`:city{_i}:` | front/author/address/postal/city |
|`:region{_i}:` | front/author/address/postal/region |
|`:country{_i}:` | front/author/address/postal/country |
|`:code{_i}:` | front/author/address/postal/code |
|`:link{_i}: _URL_` | front/link@href = _URL_ |
|`:link{_i}: _URL REL_` | front/link@href = _URL_, front/link@rel = _REL_ | REL values drawn from https://tools.ietf.org/html/rfc7669[RFC 7669]
|===

Syntax only available for RFC XML v3:

|===
| Markup | RFC XML v3 elements | Notes
|`:postal-line{_i}:` | front/author/address/postal/postalLine | Ignored in v2. Multiple lines are concatenated with `"\ "`. `:postal-line:` is mutually exclusive with the presence of `street`, `city`, `region`, `country` and `code` attributes
|===


=== Abstract

Any paragraphs following the document header are treated as the abstract
(`front/abstract`), whether or not they are in abstract style. The abstract is
terminated by either the first section header (which ends the document
preamble), or an admonition (e.g. note).

Any admonitions before the first section header are treated as notes (`front/note`).

[source,asciidoc]
----
[[abstract-id]] <1>
[abstract]
This is an abstract <2>

NOTE: This is a note <3>

[NOTE,remove-in-rfc=true] <4>
.Note 2 Title <5>
===
This is another note <3>
===
----
<1> front/abstract@anchor; attribute only available in v3
<2> front/abstract
<3> front/note
<4> front/note@removeInRFC; attribute only available in v3
<5> v2: front/note@title; v3: front/note/name


=== Sections and Subsections

[source,asciidoc]
--
[[id]] <1>
[remove-in-rfc=true,toc=include|exclude|default,sectnums] <2>
== Section title <3>
First paragraph of section <4>

Second paragraph of section <4>

=== Subsection title <5>
First paragraph of subsection <6>

==== Subsubsection title <7>
Content content content <8>
--
<1> middle/section@anchor
<2> middle/section@removeInRFC, middle/section@toc, middle/section@numbered; attributes only available in v3
<3> v2: middle/section@title; v3: middle/section/name
<4> middle/section/t
<5> v2: middle/section/section@title; v3: middle/section/section/name
<6> middle/section/section/t
<7> v2: middle/section/section/section@title; v3: middle/section/section/section/name
<8> middle/section/section/section/t


=== Cross-References

[source,asciidoc]
--
Content content content
<<crossreference>> <1>
<<crossreference,text>> <2>
<<crossreference,format=(counter|title|none|default): text>> <3>
http://example.com/[linktext] <4>
The following represent the v3 relref element
<<crossreference,section_number (of|comma|parens|bare)>> <5>
<<crossreference,section_number (of|comma|parens|bare): text>> <6>
<<crossreference#fragment,section_number (of|comma|parens|bare)>> <7>
<<crossreference#fragment,section_number (of|comma|parens|bare): text>> <8>
--
<1> `<xref target="crossreference"/>`
<2> `<xref target="crossreference">text</xref>`
<3> `<xref format="counter|title|none|default" target="crossreference">text</xref>`
<4> `<eref href="http://example.com/">linktext</eref>`
<5> `<relref displayFormat="of|comma|parens|bare" section="section_number" target="crossreference"/>`: element only available in v3
<6> `<relref displayFormat="of|comma|parens|bare" section="section_number" target="crossreference">text</relref>`: element only available in v3
<7> `<relref relative="fragment" displayFormat="of|comma|parens|bare" section="section_number" target="crossreference"/>`: element only available in v3
<8> `<relref relative="fragment" displayFormat="of|comma|parens|bare" section="section_number" target="crossreference">text</relref>`: element only available in v3


=== Indexing

[source,asciidoc]
--
This ((<indexterm>)) <1>
is visible in the text,
this one is not (((indexterm, index-subterm))). <2>
--
<1> `<iref item="indexterm">indexterm</iref>`
<2> `<iref item="indexterm" subitem="index-subterm"/>`


=== Inline formatting

[source,asciidoc]
--
Linebreak: + <1>
_Italic_ <2>
*Bold* <3>
`Monospace` <4>
~subscript~ <5>
^superscript^ <6>
[bcp14]#MUST NOT#  <7>
*MUST NOT* <8>
--
<1> That is, "+ " at the end of a line. v2: `<vspace/>`; v3: `<br/>`
<2> v2: `<spanx style="emph">Italic</spanx>`; v3: `<em>Italic</em>`
<3> v2: `<spanx style="strong">Bold</spanx>`; v3: `<strong>Bold</strong>`
<4> v2: `<spanx style="verb">Monospace</spanx>`; v3: `<tt>Monospace</tt>`
<5> v3: `<sub>subscript</sub>`. Not supported in v2; rendered as `\_subscript_`
<6> v3: `<sup>superscript</sup>`. Not supported in v2; rendered as `\^superscript^`
<7> v3: `<bcp14>MUST NOT</bcp14>`. Rendered in v2 as `<spanx style="strong">MUST NOT</spanx>`.
<8> v2: `<spanx style="strong">MUST NOT</spanx>`. v3: if document flag `:no-rfc-bold-bcp14:` is present, then `<strong>MUST NOT</strong>`, else (by default) any BCP14/RFC2119 phrase in boldface and capitals is assumed to be intended to be tagged in `<bcp14>`.


=== Paragraphs

[source,asciidoc]
--
[[id]] <1>
[keep-with-next=true,keep-with-previous=true] <2>
Paragraph text <3>
--
<1> t@anchor
<2> t@keepWithNext, t@keepWithPrevious; attributes only available in v3
<3> `<t>Paragraph text</t>`

=== Quotes (v3 only)

[source,asciidoc]
--
[[id]] <1>
[quote, attribution, citation info] <2>
Quotation <3>
--
<1> blockquote@anchor
<2> blockquote@quotedFrom, blockquote@cite. In RFC XML v3, citation info is limited to a URL.
<3> `<blockquote>Quotation</blockquote>`


=== Comments

[source,asciidoc]
--
NOTE: Any admonition inside the body of the text is a comment. <1>
// Note that actual AsciiDoc comments are ignored by the converter.

[[id]] <2>
[NOTE,display=true|false,source=name] <3>
.Note Title <4>
====
Any admonition inside the body of the text is a comment.
====
--
<1> `<cref>Any admonition inside the body of the text is a comment.</cref>`
<2> cref@anchor
<3> cref@display (not supported in v2), cref@source
<4> cref/name. Not supported in v2.


=== Source Code Listings

[source,asciidoc]
--
[[id]] <1>
.Source code listing title <2>
[source,type,src=uri,align,alt] <3>
----
begin() {
  source code listing <4>
}
----
--
<1> v3: `figure/sourcecode@anchor`, v2: `figure/artwork@anchor`
<2> v3: `figure/sourcecode@name`, v2: `figure/artwork@name`
<3> v3: `figure/sourcecode@type`, `figure/sourcecode@src` (`align` and `alt` not supported). If `src` is present, the listing is not expected to have any content: content is taken from the hyperlink in the attribute. v2: `figure/artwork@type`, `figure/artwork@src`, `figure/artwork@align`, `figure/artwork@alt`.
<4> v3: `figure/sourcecode`; v2: `figure/artwork`


=== ASCII Art and Images

[source,asciidoc]
--
[[id]] <1>
[align,alt,suppress-title] <2>
.Figure 1 <3>
====
Preamble text <4>

[[id]] <5>
[align=left|center|right,alt=alt_text,type] <6>
....
Figures are only permitted to contain listings (sourcecode), images (artwork),
or literal (artwork) <7>
....
[[id]] <5>
.Figure 2 <8>
[link=xxx,align=left|center|right,alt=alt_text,type] <9>
image::filename[] <10>

Postamble text <11>
====
--
<1> figure@anchor
<2> figure/artwork@align, figure/artwork@alt, figure@suppress-title; attributes only available in v2
<3> figure/name
<4> figure/preamble; only available in v2
<5> figure/artwork@anchor
<6> figure/artwork@align, figure/artwork@alt; figure@type (attribute only available in v2)
<7> figure/artwork
<8> figure/artwork@name; attributes only available in v2
<9> figure/artwork@src, figure/artwork@align, figure/artwork@alt; figure/artwork@type (only available in v2, intended to be a MIME type; in v3, populated as either `svg` or `binary-art` depending on file suffix)
<10> figure/artwork@src
<11> figure/postamble; only available in v2


=== Unordered and Ordered Lists

[source,asciidoc]
--
[[id]] <1>
[empty=true,compact] <2>
* Unordered list 1 <3>
* [[id]] Unordered list 2 <4>
** Nested list <5>

[[id]] <6>
[compact,start=n,group=n,arabic|loweralpha|upperralpha|lowerroman|upperroman] <7>
. A <8>
. B <8>
--
<1> v3: ul@anchor; attribute only available in v3
<2> v3: ul@empty, ul@spacing; attributes only available in v3
<3> v2: list[@style="symbols"]/t; v3: ul/li
<4> v2: list[@style="symbols"]/t@anchor, list[@style="symbols"]/t; v3: ul/li@anchor, ul/li
<5> v2: list[@style="symbols"]/t/list[@style="symbols"]/t; v3: ul/li/ul/li
<6> v3: ol@anchor; attribute only available in v3
<7> v2: list/start, list@style (`empty` and `group` not available) v3: ol@empty, ol@start, ol@group, ol@type
<8> v2: list/t; v3: ol/li


=== Definition Lists

[source,asciidoc]
--
[[id]] <1>
[horizontal,compact,hang-indent=n] <2>
A:: B <3>
--
<1> dl@anchor; attribute only available in v3
<2> dl@hanging (attribute only available in v3), dl@spacing  (attribute only available in v3), list@hangIndent  (attribute only available in v2). Note that the `compact` and `horizontal` attributes are mutually exclusive in Asciidoc.
<3> v2: list[@style="hanging"]/t@hangText, list[@style="hanging"]/t; v3: dl/dt, dl/dd

Note that Asciidoctor does not permit anchors on either definition list terms, or definition list definitions: the anchors in the following are ignored.
[source,asciidoc]
--
[[id1]] A:: [[id2]]B 
--
--

=== Tables

The converter respects the AsciiDoc (horizontal) align attributes of cells (v2, v3) and `colspan`, `rowspan` attributes (v3).

[source,asciidoc]
--
[[id]] <1>
[suppress-title,align,style] <2>
.Table Title <3>
|===
|[[id]] head | head <4>

h|header cell | body cell <5>
| | [[id]] body cell <6>

|foot | foot <7>
|===
--
<1> v2: texttable@anchor; v3: table@anchor
<2> v2: texttable@suppress-title, texttable@align, texttable@style; attributes only available in v2
<3> v2: texttable@title; v3: table/name
<4> v2: texttable/ttcol@id (attribute only available in v2), texttable/ttcol; v3: table/thead/tr/td
<5> v2: texttable/c, texttable/c; v3: table/tbody/tr/th, table/tbody/tr/td
<6> v3: table/tbody/tr/td@anchor (attribute only available in v3)
<7> v2: texttable/c; v3: table/tfoot/tr/td


=== Sidebar (v3 only)

[source,asciidoc]
--
[[id]] <1>
****
Sidebar <2>
****
--
<1> aside@anchor
<2> `<aside>Sidebar</aside>`


=== References

==== v3 References

[source,asciidoc]
--
[[id]] <1>
[bibliography]
== Normative References
* [[[crossref]]]  Reference1 <2>
[quote-title=false,target=uri,annotation=xyz] <3>
* [[[crossref2,xreftext]]] Reference2 <4>

[[id]] <1>
[bibliography]
== Informative References
* [[[crossref3]]] <5>
** [[[crossref4]]] Reference4 <6>
** [[[crossref5]]] Reference5 <6>
--
<1> back/references@anchor
<2> back/references/reference@anchor, back/references/reference/refcontent
<3> back/references/reference/refcontent@quoteTitle, back/references/reference/refcontent@target, back/references/reference/refcontent@annotation
<4> `<displayreference target=crossreference to=xyz/>`
<5> back/references/referencegroup@anchor
<6> back/references/referencegroup/reference/refcontent

==== v2 References

References for v2 are expected to be provided in raw RFC XML v2 format.

[source,asciidoc]
--
[[id]] <1>
[bibliography]
== Normative References
++++
(raw XML) <2>
++++

[[id]] <1>
[bibliography]
== Informative References
++++
(raw XML) <2>
++++
--
<1> back/references@anchor
<2> back/references/reference



=== Appendices

[source,asciidoc]
--
[[id]] <1>
[appendix]
== Appendix 1 <2>
Content <3>
--
<1> back/section@anchor
<2> v2: back/section@title; v3: back/section/name
<3> back/section/t




=== Unsupported RFC XML Elements

The following **RFC XML v3/v2** elements are not (yet) supported through
asciidoctor commands:

|===
| RFC XML element                  | RFC XML v3 | RFC XML v2
| `front/boilerplate`              | N          | N
| `iref@primary`                   | N          | N
| `reference/*` (and all children) | N/A        | N
| `reference/front`                | N          | N/A
| `table/preamble`                 | N/A        | N
| `table/postamble`                | N/A        | N
| `artwork@width`                  | N/A        | N
| `artwork@height`                 | N/A        | N
|===

=== Unsupported Asciidoctor Features

These asciidoctor features are not supported in output of these formats:

|===
| asciidoctor feature | RFC XML v2 | RFC XML v3
| http://asciidoctor.org/docs/user-manual/#quote[Quote] | rendered as normal paragraph | Y
| http://asciidoctor.org/docs/user-manual/#quote[Quote]: Non-URL Citations || Ignored
| http://asciidoctor.org/docs/user-manual/#verse[Verse] | rendered as normal paragraph | Y
| http://asciidoctor.org/docs/user-manual/#sidebar[Sidebar] | rendered as normal paragraph | Y
| http://asciidoctor.org/docs/user-manual/#index-terms[Index Term] Tertiary || Ignored
| List: http://asciidoctor.org/docs/user-manual/#numbering-styles[Ordered List numbering] `decimal`, `lowergreek` || treated as `arabic`
| http://asciidoctor.org/docs/user-manual/#callouts[Callouts] || Ignored
| http://asciidoctor.org/docs/user-manual/#discrete-headings[Floating Title] || treated as inline section
| http://asciidoctor.org/docs/user-manual/#page-break[Page Break] || Ignored
| http://asciidoctor.org/docs/user-manual/#horizontal-rules[Horizontal Rule] || Ignored
| http://asciidoctor.org/docs/user-manual/#audio[`audio`] || Ignored
| http://asciidoctor.org/docs/user-manual/#video[`video`] || Ignored
| Macro: http://asciidoctor.org/docs/user-manual/#keyboard-shortcuts[Keyboard shortcuts] || Ignored
| Macro: http://asciidoctor.org/docs/user-manual/#menu-selections[Menu selections] || Ignored
| Macro: http://asciidoctor.org/docs/user-manual/#ui-buttons[UI buttons] || Ignored
| Table: http://asciidoctor.org/docs/user-manual/#footer-row[Distinction between table body and table footer] | N | Y
| Table: http://asciidoctor.org/docs/user-manual/#header-row[Multiple table header rows] | N | Y
|===

The following tables present AsciiDoc markup, and how they map to RFC XML v2 and RFC XML v3.



== Examples

=== RFC XML v3 Example

//[source,asciidoc]
//----
include::spec/examples/example-v3.adoc[]
//----

=== RFC XML v2 Example

//[source,asciidoc]
//----
include::spec/examples/example-v2.adoc[]
//----


== Development

We follow Sandi Metz's Rules for this gem, you can read the
http://robots.thoughtbot.com/post/50655960596/sandi-metz-rules-for-developers[description of the rules here].

All new code should follow these
rules. If you make changes in a pre-existing file that violates these rules you
should fix the violations as part of your contribution.

=== Setup

Clone the repository.

```
git clone https://github.com/riboseinc/asciidoctor-rfc
```

Setup your environment.

```
bin/setup
```

Run the test suite

```
bin/rspec
```

== Contributing

First, thank you for contributing! We love pull requests from everyone. By
participating in this project, you hereby grant https://www.ribose.com[Ribose Inc.] the
right to grant or transfer an unlimited number of non exclusive licenses or
sub-licenses to third parties, under the copyright covering the contribution
to use the contribution by all means.

Here are a few technical guidelines to follow:

. Open an https://github.com/riboseinc/asciidoctor-rfc/issues[issue] to discuss a new feature.
. Write tests to support your new feature.
. Make sure the entire test suite passes locally and on CI.
. Open a Pull Request.
. https://github.com/thoughtbot/guides/tree/master/protocol/git#write-a-feature[Squash your commits] after receiving feedback.
. Party!


== Credits

This gem is developed, maintained and funded by https://www.ribose.com[Ribose Inc.]
