= AsciiDoctor-RFC
:source-highlighter: coderay
:icons: font 

https://travis-ci.org/riboseinc/asciidoctor-rfc[image:https://travis-ci.org/riboseinc/asciidoctor-rfc.svg?branch=master[Build Status]]

A gem that processes http://asciidoctor.org[Asciidoctor] input to generate RFC XML output, a format used to format RFC proposals (https://tools.ietf.org/html/rfc7991).

Generates both v3 RFC XML (https://tools.ietf.org/html/rfc7991[RFC 7991]) and v2 RFC XML (https://tools.ietf.org/html/rfc7749[RFC 7749]).

== Installation

Add this line to your application's Gemfile:

[source]
----
gem "asciidoctor-rfc"
----

And then execute:

[source]
----
$ bundle
----

Or install it yourself as:

[source]
----
$ gem install asciidoctor-rfc
----

== Usage

Converting to RFC XML is a simple as running the ./bin/asciidoctor-rfc script using Ruby and passing our AsciiDoc document as the first argument.

[source]
----
$ ruby ./bin/asciidoctor-rfc3 example.adoc  # RFC XML 3 output
$ ruby ./bin/asciidoctor-rfc2 example.adoc  # RFC XML 2 output
----

When the script completes, you should see the file `example.xml` in the same directory.

== Syntax

The converter tries to follow native Asciidoc formatting as much as possible, including built-in attributes and styles. On occasion, it introduces additional attributes for RFC XML that are not present in Asciidoc.

The following **RFC XML v2** and **RFC XML v3** elements are not supported:

* front/boilerplate
* xref@format
* iref@primary
* reference/* (all children of reference) (**v2**)
* reference/front (**v3**)
* table/preamble (**v2**)
* table/postamble (**v2**)
* artwork@width (**v2**)
* artwork@height (**v2**)

The following Asciidoc features are not supported in the mapping to **RFC XML v2** and **RFC XML v3**:

* Tertiary index terms
* quote citations other than URLs
* ordered list types decimal, lowergreek
* distinction between table body and table footer (**v2**)
* multiple table header rows  (**v2**)
* audio
* colist
* floating title
* page break
* thematic break
* video
* inline button
* inline keyboard
* inline menu
* callout
* quote, verse (**v2**: rendered as normal paragraph)
* sidebar (**v2**: rendered as normal paragraph)

The following tables present Asciidoc markup, and how they map to RFC XML v2 and RFC XML v3.

=== Document header

The Asciidoc document header consists of a title, an inline listing of authors, and a list of document attributes (with no blank lines permitted). The attributes listed in the following are the only attributes recognised for conversion into RFC XML.

The author listing is of the following format:

```
Firstname Middlename(s) Lastname <Email>; Firstname Middlename(s) Lastname <Email>; Firstname Middlename(s) Lastname <Email>
```

The author listing is optional, and more detailed author attributes are given in the body of document attributes.

|===
|Asciidoc markup | v2 element | v3 element | Note

|`= Document Title` | front/title | front/title |
|Author listing | front/author@fullname, front/author@surname, front/author/address/email | front/author@fullname, front/author@surname, front/author/address/email |
|`:abbrev:` | front/title@abbrev | front/title@abbrev |
|`:ipr:` | rfc@ipr | rfc@ipr |
|`:obsoletes:` | rfc@obsoletes | rfc@obsoletes | no need to insert list in brackets, as with MMark; assumed delimited by comma+space
|`:updates:` | rfc@updates | rfc@updates | no need to insert list in brackets, as with MMark; assumed delimited by comma+space
|`:submission-type:` | rfc@submissionType |  rfc@submissionType | default value is `IETF`
|`:index-include:` | | rfc@indexInclude |
|`:ipr-extract:` | rfc@iprExtract | rfc@iprExtract |
|`:sort-refs:` | | rfc@iprExtract |
|`:sym-refs:` | | rfc@symRefs |
|`:toc-include:` | | rfc@tocInclude |
|`:name:` rfc-_nnnn_ | | front/seriesInfo@value; front/seriesInfo@name = `RFC` |
|`:name:` Internet-Draft-_Name_ | | front/seriesInfo@value; front/seriesInfo@name = `Internet-Draft` |
|`:status:` | | front/seriesInfo@status | status of this document
|`:intendedstatus:` | | front/seriesInfo@status | status of Internet Draft, once published as RFC. Given in `<seriesinfo>` element with an empty `name` attribute.
|`:rfcstatus:` full-standard\|bcp\|fyi _number_ | | front/seriesInfo@status, front/seriesInfo@value = number | Given in `<seriesinfo>` element with empty `name` attribute
|`:rfcstatus:` info\|exp\|historic | | front/seriesInfo@status | Given in `<seriesinfo>` element with empty `name` attribute
|`:stream:` | | front/seriesInfo@stream | default value is `IETF`
|`:category:`| rfc@category | | 
|`:consensus:` | rfc@consensus | |
|`:doc-name:` | rfc@docName | |
|`:number:` | rfc@number | |
|`:series-no:` | rfc@seriesNo | |
|`:xmllang:` | rfc@xml:lang | |
|`:fullname:` | front/author@fullname | front/author@fullname |
|`:forename_initials:` | front/author@initials | front/author@initials |distinct from Asciidoc `:initials:` attribute, which includes surname
|`:lastname:` |front/author@surname | front/author@surname |
|`:role:` |front/author@role | front/author@role |
|`:organization:` |front/author/ organization | front/author/ organization |
|`:organization_abbrev:` |  front/author/ organization@abbrev | |
|`:email:` |front/author/ address/email | front/author/ address/email |
|`:fax:` |front/author/ address/facsimile | front/author/ address/facsimile |
|`:uri:` |front/author/ address/uri | front/author/ address/uri |
|`:phone:` |front/author/ address/phone | front/author/ address/phone |
|`:postal-line:` | | front/author/ address/postal/postalLine | multiple lines are concatenated with "\ ". postal-line is mutually exclusive with the presence of street, city, region, country and code attributes
|`:street:` |front/author/ address/postal/street | front/author/ address/postal/street | multiple lines are concatenated with "\ ".
|`:city:` |front/author/ address/postal/city | front/author/ address/city |
|`:region:` |front/author/ address/postal/region | front/author/ address/region |
|`:country:` |front/author/ address/postal/country | front/author/ address/country |
|`:code:` |front/author/ address/postal/code | front/author/ address/code |
|`:fullname_2:` | front/author@fullname | front/author@fullname | Attributes of a second, third etc author are given by appending `_2`, `_3` etc to the attribute name
|`:forename_initials_2:` | front/author@initials | front/author@initials |distinct from Asciidoc `:initials:` attribute, which includes surname
|`:lastname_2:` |front/author@surname | front/author@surname |
|`:role_2:` |front/author@role | front/author@role |
|`:organization_2:` |front/author/ organization | front/author@organization |
|`:organization_abbrev_2:` |  front/author/ organization@abbrev | |
|`:email_2:` |front/author/ address/email | front/author/ address/email |
|`:fax_2:` |front/author/ address/facsimile | front/author/ address/facsimile |
|`:uri_2:` |front/author/ address/uri | front/author/ address/uri |
|`:phone_2:` |front/author/ address/phone | front/author/ address/phone |
|`:postal-line_2:` | | front/author/ address/postal/postalLine | multiple lines are concatenated with "\ ". postal-line is mutually exclusive with the presence of street, city, region, country and code attributes
|`:street_2:` |front/author/ address/postal/street | front/author/ address/postal/street | multiple lines are concatenated with "\ ".
|`:city_2:` |front/author/ address/postal/city | front/author/ address/city |
|`:region_2:` |front/author/ address/postal/region | front/author/ address/region |
|`:country_2:` |front/author/ address/postal/country | front/author/ address/country |
|`:code_2:` |front/author/ address/postal/code | front/author/ address/code |
|`:revdate:` |front/date@day, front/date@month, front/date@year | front/date@day, front/date@month, front/date@year | For consistency with Asciidoc, `:revdate:` is given as an ISO 8601 date; the converter breaks it down into day, month name and year
|`:area:` | front/area| front/area | comma delimited
|`:workgroup:` |front/workgroup | front/workgroup | comma delimited
|`:keyword:` |front/keyword | front/keyword | comma delimited
|`:link:` _URL_ | | front/link@href = _URL_ |
|`:link:` _URL REL_ | | front/link@href = _URL_, front/link@rel = _REL_ | REL values drawn from https://tools.ietf.org/html/rfc7669[RFC 7669]
|===

=== Preamble

Any paragraphs following the document header are treated as the abstract (`front/abstract`), whether or not they are in abstract style. The abstract is terminated by either the first section header (which ends the document preamble), or an admonition (e.g. note).

Any admonitions before the first section header are treated as notes (`font/note`).

[source,asciidoc]
--
[[abstract-id]] <1>
[abstract]
This is an abstract <2> 

NOTE: This is a note <3>

[NOTE,remove-in-rfc=true] <4>
.Note 2 Title <5>
===
This is another note <3>
===
--
<1> front/abstract@anchor; attribute only available in v3
<2> front/abstract
<3> front/note
<4> front/note@removeInRFC; attribute only available in v3
<5> v2: front/note@title; v3: front/note/name

=== Sections and subsections

[source,asciidoc]
--
[[id]] <1> 
[remove-in-rfc=true,toc=include|exclude|default,sectnums] <2> 
== Section title <3>
First paragraph of section <4>

Second paragraph of section <4>

=== Subsection title <5>
First paragraph of subsection <6>

==== Subsubsection title <7>
Content content content <8>
--
<1> middle/section@anchor
<2> middle/section@removeInRFC, middle/section@toc, middle/section@numbered; attributes only available in v3
<3> v2: middle/section@title; v3: middle/section/name
<4> middle/section/t
<5> v2: middle/section/section@title; v3: middle/section/section/name
<6> middle/section/section/t
<7> v2: middle/section/section/section@title; v3: middle/section/section/section/name
<8> middle/section/section/section/t

=== Crossreferences

[source,asciidoc]
--
Content content content 
<<crossreference>> <1>
<<crossreference,text>> <2>
http://example.com/[linktext] <3>
--
<1> `<xref target="crossreference"/>`
<2> `<xref target="crossreference">text</xref>`
<3> `<eref href="http://example.com/">linktext</eref>`

=== Indexing

[source,asciidoc]
--
This ((<indexterm>)) <1>
is visible in the text,
this one is not (((indexterm, index-subterm))). <2>
--
<1> `<iref item="indexterm">indexterm</iref>`
<2> `<iref item="indexterm" subitem="index-subterm"/>`

=== Inline formatting

[source,asciidoc]
--
Linebreak: + <1>
_Italic_ <2>
*Bold* <3>
`Monospace` <4>
~subscript~ <5>
^superscript^ <6>
[bcp14]#MUST NOT#  <7>
--
<1> That is, "+ " at the end of a line. v2: `<vspace/>`; v3: `<br/>`
<2> v2: `<spanx style="emph">Italic</spanx>`; v3: `<em>Italic</em>`
<3> v2: `<spanx style="strong">Bold</spanx>`; v3: `<strong>Bold</strong>`
<4> v2: `<spanx style="verb">Monospace</spanx>`; v3: `<tt>Monospace</tt>`
<5> v3: `<sub>subscript</sub>`. Not supported in v2; rendered as `\_subscript_`
<6> v3: `<sup>superscript</sup>`. Not supported in v2; rendered as `\^superscript^`
<7> v3: `<bcp14>MUST NOT</bcp14>`. Not supported in v2.


=== Paragraphs

[source,asciidoc]
--
[[id]] <1>
[keep-with-next=true,keep-with-previous=true] <2> 
Paragraph text <3>
--
<1> t@anchor
<2> t@keepWithNext, t@keepWithPrevious; attributes only available in v3
<3> `<t>Paragraph text</t>`

=== Quotes (v3 only)

[source,asciidoc]
--
[[id]] <1>
[quote, attribution, citation info] <2> 
Quotation <3>
--
<1> blockquote@anchor
<2> blockquote@quotedFrom, blockquote@cite. In RFC XML v3, citation info is limited to a URL.
<3> `<blockquote>Quotation</blockquote>`

=== Comments

[source,asciidoc]
--
NOTE: Any admonition inside the body of the text is a comment. <1>
// Note that actual Asciidoc comments are ignored by the converter.

[[id]] <2>
[NOTE,display=true|false,source=name] <3> 
.Note Title <4>
====
Any admonition inside the body of the text is a comment.
====
--
<1> `<cref>Any admonition inside the body of the text is a comment.</cref>`
<2> cref@anchor
<3> cref@display (not supported in v2), cref@source
<4> cref/name. Not supported in v2.

=== Source code listings

[source,asciidoc]
--
[[id]] <1>
.Source code listing title <2>
[source,type,src=uri,align,alt] <3>
----
begin() { 
  Source code listing <4>
}
----
--
<1> v2: figure/artwork@anchor; v3: figure/sourcecode@anchor
<2> v2: figure/artwork@name; v3: figure/sourcecode@name
<3> v2: figure/artwork@type, figure/artwork@src, figure/artwork@align, figure/artwork@alt; v3: figure/sourcecode@type, figure/sourcecode@src (`align` and `alt` not supported). If `src` is present, the listing is not expected to have any content: content is taken from the hyperlink in the attribute.
<4> v2: figure/artwork; v3: figure/sourcecode

=== ASCII Art and Images

[source,asciidoc]
--
[[id]] <1>
[align,alt,suppress-title] <2>
.Figure 1 <3>
====
Preamble text <4>

[[id]] <5>
[align=left|center|right,alt=alt_text,type] <6>
....
Figures are only permitted to contain listings (sourcecode), images (artwork), 
or literal (artwork) <7>
....
[[id]] <5>
.Figure 2 <8>
[link=xxx,align=left|center|right,alt=alt_text,type] <9>
image::filename[] <10>

Postamble text <11>
====
--
<1> figure@anchor
<2> figure/artwork@align, figure/artwork@alt, figure@supress-title; attributes only available in v2
<3> figure/name
<4> figure/preamble; only available in v2
<5> figure/artwork@anchor
<6> figure/artwork@align, figure/artwork@alt; figure@type (attribute only available in v2)
<7> figure/artwork
<8> figure/artwork@name; attributes only available in v2
<9> figure/artwork@src, figure/artwork@align, figure/artwork@alt; figure/artwork@type (only available in v2, intended to be a MIME type; in v3, populated as either `svg` or `binary-art` depending on file suffix)
<10> figure/artwork@src
<11> figure/postamble; only available in v2


=== Unordered and Ordered Lists

[source,asciidoc]
--
[[id]] <1>
[empty=true,compact] <2>
* Unordered list 1 <3>
* [[id]] Unordered list 2 <4>
** Nested list <5>

[[id]] <6>
[compact,start=n,group=n,arabic|loweralpha|upperralpha|lowerroman|upperroman] <7>
. A <8>
. B <8>
--
<1> v3: ul@anchor; attribute only available in v3
<2> v3: ul@empty, ul@spacing; attributes only available in v3
<3> v2: list[@style="symbols"]/t; v3: ul/li
<4> v2: list[@style="symbols"]/t@anchor, list[@style="symbols"]/t; v3: ul/li@anchor, ul/li
<5> v2: list[@style="symbols"]/t/list[@style="symbols"]/t; v3: ul/li/ul/li
<6> v3: ol@anchor; attribute only available in v3
<7> v2: list/start, list@style (`empty` and `group` not available) v3: ol@empty, ol@start, ol@group, ol@type
<8> v2: list/t; v3: ol/li

=== Definition Lists

[source,asciidoc]
--
[[id]] <1>
[horizontal,compact,hang-indent=n] <2>
A:: B <3>
[[id1]] A:: [[id2]] B <4>
--
<1> dl@anchor; attribute only available in v3
<2> dl@hanging (attribute only available in v3), dl@spacing  (attribute only available in v3), list@hangIndent  (attribute only available in v2)
<3> v2: list[@style="hanging"]/t@hangText, list[@style="hanging"]/t; v3: dl/dt, dl/dd
<4> v2: list[@style="hanging"]/t@anchor, list[@style="hanging"]/t@anchor, list[@style="hanging"]/t; v3: dl/dt@anchor, dl/dd@anchor. In v2, the latest of the anchors will be used.

=== Tables

The converter respects the Asciidoc (horizontal) align attributes of cells (v2, v3) and colspan, rowspan attributes (v3).

[source,asciidoc]
--
[[id]] <1>
[suppress-title,align,style] <2>
.Table Title <3>
|===
|[[id]] head | head <4>

h|header cell | body cell <5>
| | [[id]] body cell <6>

|foot | foot <7>
|===
--
<1> v2: texttable@anchor; v3: table@anchor
<2> v2: texttable@supress-title, texttable@align, texttable@style; attributes only available in v2
<3> v2: texttable@title; v3: table/name
<4> v2: texttable/ttcol@id (attribute only available in v2), texttable/ttcol; v3: table/thead/tr/td
<5> v2: texttable/c, texttable/c; v3: table/tbody/tr/th, table/tbody/tr/td
<6> v3: table/tbody/tr/td@anchor (attribute only available in v3)
<7> v2: texttable/c; v3: table/tfoot/tr/td  

=== Sidebar (v3 only)

[source,asciidoc]
--
[[id]] <1>
****
Sidebar <2>
****
--
<1> aside@anchor
<2> `<aside>Sidebar</aside>`

=== Referencecs (v2)
References for v2 are expected to be provided in raw RFC XML v2 format.

[source,asciidoc]
--
[[id]] <1>
[bibliography]
== Normative References
++++
(raw XML) <2>
++++ 

[[id]] <1>
[bibliography]
== Informative References
++++
(raw XML) <2>
++++ 
--
<1> back/references@anchor
<2> back/references/reference

=== References (v3)

[source,asciidoc]
--
[[id]] <1>
[bibliography]
== Normative References
* [[[crossref]]]  Reference1 <2>
[quote-title=false,target=uri,annotation=xyz] <3>
* [[[crossref2,xreftext]]] Reference2 <4>

[[id]] <1>
[bibliography]
== Informative References
* [[[crossref3]]] <5>
** [[[crossref4]]] Reference4 <6>
** [[[crossref5]]] Reference5 <6>
--
<1> back/references@anchor
<2> back/references/reference@anchor, back/references/reference/refcontent
<3> back/references/reference/refcontent@quoteTitle, back/references/reference/refcontent@target,  back/references/reference/refcontent@annotation
<4> `<displayreference target=crossreference to=xyz/>`
<5> back/references/referencegroup@anchor
<6> back/references/referencegroup/reference/refcontent

=== Appendices

[source,asciidoc]
--
[[id]] <1>
[appendix]
== Appendix 1 <2> 
Content <3>
--
<1> back/section@anchor
<2> v2: back/section@title; v3: back/section/name
<3> back/section/t





== Example, v3


[source,asciidoc]
--
= A Standard for the Transmission of IP Datagrams on Avian Carriers
David Waitzman <dwaitzman@BBN.COM>; Nick Nicholas <opoudjis@gmail.com>
:abbrev: IP Datagrams on Avian Carriers
:obsoletes: 10, 120
:updates: 2010, 2120
:name: rfc-1149
:rfcstatus: full-standard 1149
:ipr: trust200902
:area: Internet
:workgroup: Network Working Group
:keyword: this, that
:revdate: 1990-04-01T00:00:00Z
:organization: BBN STC
:phone: (617) 873-4323
:uri: http://bbn.com
:street: 10 Moulton Street
:city: Cambridge
:code: MA 02238
:organization_2: BBN STC
:phone_2: (617) 873-4323
:street_2: 10 Moulton Street
:city_2: Cambridge
:code_2: MA 02238
:uri_2: http://opoudjis.net
:link: http://example1.com,http://example2.com author

[abstract]
Avian carriers can provide high delay, low throughput, and low
altitude service.  The connection topology is limited to a single
point-to-point path for each carrier, used with standard carriers,
but many carriers can be used without significant interference with
each other, outside of early spring.  This is because of the 3D ether 
space available to the carriers, in contrast to the 1D ether used by
IEEE802.3.  The carriers have an intrinsic collision avoidance
system, which increases availability.  Unlike some network
technologies, such as packet radio, communication is not limited to
line-of-sight distance.  Connection oriented service is available in
some cities, usually based upon a central hub topology.

NOTE: Yes, this is an April Fool's RFC.

[[frame]]
== Frame Format

The IP _datagram_ is *printed*, on a small scroll of paper, in
hexadecimal, with each octet separated by whitestuff and blackstuff.
The scroll of paper is wrapped around one leg of the avian carrier.
A band of duct tape is used to secure the datagram's edges.  The
bandwidth is limited to the leg length.  The MTU is variable, and
paradoxically, generally increases with increased carrier age.  A
typical MTU is 256 milligrams.  Some datagram padding may be needed.<<gof,2>>

Upon receipt, the duct tape is removed and the paper copy of the
datagram is optically scanned into a electronically transmittable
form.<<xxx>>

This document extends OpenPGP and its ECC extension to support SM2, SM3 and SM4:

* support the SM3 hash algorithm for data validation purposes
* support signatures utilizing the combination of SM3 with other digital
  signing algorithms, such as RSA, ECDSA and SM2
* support the SM2 asymmetric encryption algorithm for public key
  operations
* support usage of SM2 in combination with supported hash algorithms, such as
  SHA-256 and SM3
* support the SM4 symmetric encryption algorithm for data protection purposes
* defines the OpenPGP profile "OSCCA-SM234" to enable usage of OpenPGP
  in an OSCCA-compliant manner.
  
Algorithm-Specific Fields for SM2DSA keys:

* a variable-length field containing a curve OID, formatted
  as follows:
.. a one-octet size of the following field; values 0 and
   0xFF are reserved for future extensions
.. octets representing a curve OID.
*  MPI of an EC point representing a public key
  
  
===  Definitions

OSCCA-compliant:: All cryptographic algorithms used are compliant with OSCCA  regulations.
SM2DSA:: The elliptic curve digital signature algorithm. <<xxxx>>
SM2KEP:: The elliptic curve key exchange protocol.
SM2PKE:: The public key encryption algorithm.

==== Elliptic Curve Formula

[stem]
++++
y^2 = x^3 + ax + b
++++

==== Curve Parameters

[[curveparam1] 
.Curve Parameters Listing
====
....
p   = FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF
      FFFFFFFF 00000000 FFFFFFFF FFFFFFFF
a   = FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF
      FFFFFFFF 00000000 FFFFFFFF FFFFFFFC
b   = 28E9FA9E 9D9F5E34 4D5A9E4B CF6509A7
      F39789F5 15AB8F92 DDBCBD41 4D940E93
n   = FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF
      7203DF6B 21C6052B 53BBF409 39D54123
x_G = 32C4AE2C 1F198119 5F990446 6A39C994
      8FE30BBF F2660BE1 715A4589 334C74C7
y_G = BC3736A2 F4F6779C 59BDCEE3 6B692153
      D0A9877C C62A4740 02DF32E5 2139F0A0
....
====

== Supported Algorithms

=== Public Key Algorithms

The SM2 algorithm is supported with the following extension.

NOTE: ECDH is defined in Section 8 of this document.

The following public key algorithm IDs are added to expand Section
9.1 of RFC4880, "Public-Key Algorithms":

.Table 2
|===
|ID | Description of Algorithm

|TBD | SM2
|===



== Security Considerations

Security is not generally a problem in normal operation, but special +
measures [bcp14]#MUST# be taken (such as data encryption) when avian carriers
are used in a tactical environment.<<pp>> 

[bibliography]
== References

* [[[pp]]]
** [[[xxx]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
  From Journeyman to Master. Addison-Wesley. 1999.
** [[[xxxx]]] Personal communication.
* [[[gof,2]]] Erich Gamma, Richard Helm, Ralph Johnson & John Vlissides. Design Patterns:
  Elements of Reusable Object-Oriented Software. Addison-Wesley. 1994.
--




== Example, v2

[source,asciidoc]
--
\= A Standard for the Transmission of IP Datagrams on Avian Carriers
David Waitzman <dwaitzman@BBN.COM>; Nick Nicholas <opoudjis@gmail.com>
:abbrev: IP Datagrams on Avian Carriers
:obsoletes: 10, 120
:updates: 2010, 2120
:category: info
:docName: rfc-1149
:ipr: trust200902
:area: Internet
:workgroup: Network Working Group
:keyword: this, that
:revdate: 1990-04-01T00:00:00Z
:organization: BBN STC
:phone: (617) 873-4323
:uri: http://bbn.com
:street: 10 Moulton Street
:city: Cambridge
:code: MA 02238
:organization_2: BBN STC
:phone_2: (617) 873-4323
:street_2: 10 Moulton Street
:city_2: Cambridge
:code_2: MA 02238
:uri_2: http://opoudjis.net



[abstract]
Avian carriers can provide high delay, low throughput, and low
altitude service.  The connection topology is limited to a single
point-to-point path for each carrier, used with standard carriers,
but many carriers can be used without significant interference with
each other, outside of early spring.  This is because of the 3D ether 
space available to the carriers, in contrast to the 1D ether used by
IEEE802.3.  The carriers have an intrinsic collision avoidance
system, which increases availability.  Unlike some network
technologies, such as packet radio, communication is not limited to
line-of-sight distance.  Connection oriented service is available in
some cities, usually based upon a central hub topology.

NOTE: Yes, this is an April Fool's RFC.

[[frame]]
== Frame Format

The IP _datagram_ is *printed*, on a small scroll of paper, in
hexadecimal, with each octet separated by whitestuff and blackstuff.
The scroll of paper is wrapped around one leg of the avian carrier.
A band of duct tape is used to secure the datagram's edges.  The
bandwidth is limited to the leg length.  The MTU is variable, and
paradoxically, generally increases with increased carrier age.  A
typical MTU is 256 milligrams.  Some datagram padding may be needed.<<RFC7253>>

Upon receipt, the duct tape is removed and the paper copy of the
datagram is optically scanned into a electronically transmittable
form.<<RFC7253>>

This document extends OpenPGP and its ECC extension to support SM2, SM3 and SM4:

* support the SM3 hash algorithm for data validation purposes
* support signatures utilizing the combination of SM3 with other digital
  signing algorithms, such as RSA, ECDSA and SM2
* support the SM2 asymmetric encryption algorithm for public key
  operations
* support usage of SM2 in combination with supported hash algorithms, such as
  SHA-256 and SM3
* support the SM4 symmetric encryption algorithm for data protection purposes
* defines the OpenPGP profile "OSCCA-SM234" to enable usage of OpenPGP
  in an OSCCA-compliant manner.
  
Algorithm-Specific Fields for SM2DSA keys:

* a variable-length field containing a curve OID, formatted
  as follows:
.. a one-octet size of the following field; values 0 and
   0xFF are reserved for future extensions
.. octets representing a curve OID.
*  MPI of an EC point representing a public key
  
  
===  Definitions

OSCCA-compliant:: All cryptographic algorithms used are compliant with OSCCA  regulations.
SM2DSA:: The elliptic curve digital signature algorithm. <<ISO.IEC.10118-3>>
SM2KEP:: The elliptic curve key exchange protocol.
SM2PKE:: The public key encryption algorithm.==== Elliptic Curve Formula

==== Elliptic Curve Formula

[stem]
++++
y^2 = x^3 + ax + b
++++

==== Curve Parameters

[[curveparam1] 
.Curve Parameters Listing
====
....
p   = FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF
      FFFFFFFF 00000000 FFFFFFFF FFFFFFFF
a   = FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF
      FFFFFFFF 00000000 FFFFFFFF FFFFFFFC
b   = 28E9FA9E 9D9F5E34 4D5A9E4B CF6509A7
      F39789F5 15AB8F92 DDBCBD41 4D940E93
n   = FFFFFFFE FFFFFFFF FFFFFFFF FFFFFFFF
      7203DF6B 21C6052B 53BBF409 39D54123
x_G = 32C4AE2C 1F198119 5F990446 6A39C994
      8FE30BBF F2660BE1 715A4589 334C74C7
y_G = BC3736A2 F4F6779C 59BDCEE3 6B692153
      D0A9877C C62A4740 02DF32E5 2139F0A0
....
====

== Supported Algorithms

=== Public Key Algorithms

The SM2 algorithm is supported with the following extension.

NOTE: ECDH is defined in Section 8 of this document.

The following public key algorithm IDs are added to expand Section
9.1 of RFC4880, "Public-Key Algorithms":

.Table 2
|===
|ID | Description of Algorithm

|TBD | SM2
|===



== Security Considerations

Security is not generally a problem in normal operation, but special +
measures **MUST** be taken (such as data encryption) when avian carriers
are used in a tactical environment.<<RFC7253>>, <<ISO.IEC.10118-3>>

[bibliography]
== References
++++
<reference anchor='ISO.IEC.10118-3' target='https://www.iso.org/standard/67116.html'>
  <front>
    <title>ISO/IEC FDIS 10118-3 -- Information technology -- Security techniques -- Hash-functions -- Part 3: Dedicated hash-functions</title>
    <author>
      <organization>International Organization for Standardization</organization>
      <address>
        <postal>
          <street>BIBC II</street>
          <street>Chemin de Blandonnet 8</street>
          <street>CP 401</street>
          <city>Vernier</city>
          <region>Geneva</region>
          <code>1214</code>
          <country>Switzerland</country>
        </postal>
        <phone>+41 22 749 01 11</phone>
        <email>central@iso.org</email>
        <uri>https://www.iso.org/</uri>
      </address>
    </author>
    <date day='15' month='September' year='2017'/>
  </front>
</reference>

<reference anchor='RFC7253' target='https://tools.ietf.org/html/rfc7253'>
  <front>
    <title>Guidelines for Writing an IANA Considerations Section in RFCs</title>
    <author initials="T." surname="Krovetz">
      <organization>Sacramento State</organization>
    </author>
    <author initials="P." surname="Rogaway">
      <organization>UC Davis</organization>
    </author>
    <date month='May' year='2014'/>
  </front>
  <seriesInfo name="RFC" value="7253"/>
</reference>
++++







== Development

We are following Sandi Metz's Rules for this gem, you can read the
http://robots.thoughtbot.com/post/50655960596/sandi-metz-rules-for-developers[description of the rules here].
All new code should follow these
rules. If you make changes in a pre-existing file that violates these rules you
should fix the violations as part of your contribution.

=== Setup

Clone the repository.

```
git clone https://github.com/riboseinc/asciidoctor-rfc
```

Setup your environment.

```
bin/setup
```

Run the test suite

```
bin/rspec
```

== Contributing

First, thank you for contributing! We love pull requests from everyone. By
participating in this project, you hereby grant https://www.ribose.com[Ribose Inc.] the
right to grant or transfer an unlimited number of non exclusive licenses or
sub-licenses to third parties, under the copyright covering the contribution
to use the contribution by all means.

Here are a few technical guidelines to follow:

. Open an https://github.com/riboseinc/ribose-ruby/issues[issue] to discuss a new feature.
. Write tests to support your new feature.
. Make sure the entire test suite passes locally and on CI.
. Open a Pull Request.
. https://github.com/thoughtbot/guides/tree/master/protocol/git#write-a-feature[Squash your commits] after receiving feedback.
. Party!

== Credits

This gem is developed, maintained and funded by https://www.ribose.com[Ribose Inc.]

