= Your MIB module document name
Editor name <Editor email>
:doctype: internet-draft
:status: historic
:name: Your MIB Document name here rev07
:ipr: trust200902
:abbrev: Your MIB Module document name
:fullname: Editor name
:lastname: name
:forename_initials: Y
:role: editor
:organization: Editor affiliation
:street: Editor affiliation address
:city: Editor affiliation address
:country: Editor affiliation address
:phone: Editor address
:email: Editor email
:revdate: 2008-01-01
:area: Operations & Management Area
:workgroup: Internet Engineering Task Force
:keyword: Network Management,Management Information Base,MIB,SMIv2
:smart-quotes: false
:compact: yes
:subcompact: no
:rfcedstyle: yes
:comments: yes
:inline: yes

[abstract]

(In RFC XML v2, an abstract cannot begin with a note!)

[[CREF1: This template is for authors of IETF specifications containing MIB
  modules.  This template can be used as a starting point to produce
  specifications that comply with the Operations & Management Area
  guidelines for MIB module internet drafts. Throughout the template, the marker "[TEMPLATE TODO]" is used as a placeholder to indicate an
  element or text that requires replacement or removal. All the places with [TEMPLATE TODO] markers 
  should  be replaced or removed before the document is submitted.]]
  
This memo defines a portion of the Management Information Base (MIB)
for use with network management protocols. In particular it defines
objects for managing [TEMPLATE TODO].
      

[[CREF2: [TEMPLATE TODO]: describe what functionality will be managed using this MIB
 module. It can be good to mention the protocol being managed, and
 whether there is a particular aspect of the protocol to be managed, or a
 particular goal of the module. But keep it brief. Remember, don't put any citations 
 in the abstract, and expand your  acronyms. ]]

 
[NOTE]
.Foreword to template users
====
This template is intended to help authors write the surrounding text needed in a
MIB module internet draft, but does not provide a template for writing 
the MIB module itself.

Throughout this template, the marker "[TEMPLATE TODO]" is used as a reminder
to the template user to indicate an element or text that requires
replacement or removal by the template user before submission to the
internet draft editor. All [TEMPLATE TODO] markers should be resolved and removed
before you submit your document to the internet-draft editor.

For updated information on MIB module guidelines and templates, see
<<RFC4181>> and the OPS Area web page and wiki.

For information on writing internet drafts or RFCs, see
\http://www.ietf.org/ietf/1id-guidelines.txt and 
RFC2223(bis) <<RFC2223>>, and look
at \http://www.ietf.org/ID-Checklist.html for issues to note when writing
drafts.

This template is not meant to be a complete list of everything
needed to write MIB module internet drafts, but to summarize the often-needed
basic features to get a document containing a MIB module started. An
important purpose of the template is to aid authors in developing an
internet draft that is laid out in a manner consistent with other internet 
drafts containing MIB modules. Internet drafts submitted for advancement 
to the standards track typically require review by a MIB Doctor. This 
template standardizes the layout and naming of sections, includes the 
appropriate boilerplate text, and facilitates the development of tools 
to automate the checking of MIB module internet drafts, to speed the WG 
and IESG review processes.

An XML2RFC template is also available. For information on XML2RFC, see
RFC2629 <<RFC2629>>, and documentation available at
\http://xml.resource.org. The XML2RFC version includes
advice describing how to fill in each section of the template. XML2RFC generates the 
actual internet-draft from your information, and automatically handles getting up-to-date 
boilerplates, references, and it handles many idnits issues.

Within the template, there is reference to a SAMPLE-MIB; all references 
to SAMPLE-MIB should be removed from your internet draft, and should be 
replaced by references to your MIB module, as appropriate.

[TEMPLATE TODO] THIS section, the complete section entitled "Note: Foreword to
template users" should be removed by the template user from their
document before submission.

[TEMPLATE TODO] Remove all page headings from the template document, and
replace them with the appropriate headings for your internet draft.
====

[NOTE]
.Note to RFC Editor re: [TEMPLATE TODO] markers  
====
Note to RFC Editor: When a document is developed using this template, the editor of the 
document should replace or remove all the places marked [TEMPLATE TODO] before submitting the document.
If there are still [TEMPLATE TODO] markers, please send the document back to the editor.
====

== Introduction
This memo defines a portion of the Management Information Base (MIB)
for use with network management protocols. In particular it defines
objects for managing the [TEMPLATE TODO].

[[CREF3: [TEMPLATE TODO]: describe what functionality will be managed using this MIB
module. Include citations for protocol specifications, architectures, related MIB modules, and protocol-specific
management requirements. Provide an overview of why a MIB module is appropriate for this protocol,  whether there is a 
particular aspect of the protocol to be managed, and how the module is expected to be used to 
achieve particular goals. Highlight anything 'different' about the module. For example, 
a read-only MIB module.]]

== The Internet-Standard Management Framework
[[CREF4: The title and text for this section has been copied from the 
official boilerplate, and should not be modified unless the official boilerplate text 
from the OPS Area web site has changed. See RFC4818 
section 3.1 for a discussion of the boilerplate section.]]

For a detailed overview of the documents that describe the current
Internet-Standard Management Framework, please refer to section 7 of RFC
3410 <<RFC3410>>.

Managed objects are accessed via a virtual information store, termed
the Management Information Base or MIB. MIB objects are generally
accessed through the Simple Network Management Protocol (SNMP). Objects
in the MIB are defined using the mechanisms defined in the Structure of
Management Information (SMI). This memo specifies a MIB module that is
compliant to the SMIv2, which is described in STD 58, RFC 2578 <<RFC2578>>, STD 58, RFC 2579 <<RFC2579>> and STD 58, RFC 2580 <<RFC2580>>.

== Conventions
[[CREF5: [TEMPLATE TODO] This boilerplate should be used if the RFC2119 key words 
are used in the internet draft. The text in this section has been 
copied from the official boilerplate, and should not be modified. ]]

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
"SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
document are to be interpreted as described in BCP 14, RFC 2119 <<RFC2119>>.
      
== Overview
[[CREF6: [TEMPLATE TODO] The narrative part should include an overview section that
describes the scope and field of application of the MIB modules
defined by the specification.  See RFC4181 section 3.2 for a
discussion of the Narrative section.  ]]

== Structure of the MIB Module

[[CREF7: [TEMPLATE TODO] The narrative part SHOULD include one or more sections to
briefly describe the structure of the MIB modules defined in the
specification.]]


=== Textual Conventions
[[CREF8: [TEMPLATE TODO] describe the textual conventions defined in the MIB
module, and their purpose. It may be helpful to highlight any textual conventions
imported from partner documents. Generic and Common Textual Conventions can be found summarized at 
the OPS Area web site. If there are no textual conventions used in your MIB module,
this section should be removed.]]

=== The [TEMPLATE TODO] Subtree
[[CREF9: [TEMPLATE TODO] copy this section for each subtree in the MIB module, and
describe the purpose of the subtree. For example, "The fooStats subtree
provides information for identifying fault conditions and performance
degradation of the foo functionality."]]

=== The Notifications Subtree
[[CREF10: [TEMPLATE TODO] describe the notifications defined in the MIB module, and
their purpose. Include a discussion of congestion control. You might
want to discuss throttling as well. See RFC2914.]]

=== The Table Structures
[[CREF11: [TEMPLATE TODO] Describe the tables in the MIB module, their purpose, and their
reltionship to each other. If the row in one table is related to a row in 
another table, what happens when one of the rows is deleted? Should the 
related row be deleted as well? Consider both directions.]]

== Relationship to Other MIB Modules
[[CREF12: [TEMPLATE TODO]: The narrative part should include a section that specifies the
relationship (if any) of the MIB modules contained in this internet drafts to
other standards, particularly to standards containing other MIB
modules. If the MIB modules defined by the specification import
definitions from other MIB modules or are always implemented in
conjunction with other MIB modules, then those facts should be noted in
the narrataive section, as should any special interpretations of objects
in other MIB modules. Note that citations may NOT be put into the MIB
module portions of the internet draft, but documents used for Imported items
are Normative references, so the citations should exist in the narrative
section of the internet draft. The preferred 
way to fill in a REFERENCE clause in a MIB module is of the form: "Guidelines 
for Writing an IANA Considerations Section in RFCs", RFC2434, section 2.3.]]

=== Relationship to the [TEMPLATE TODO] MIB
[[CREF13: Example: The Interface MIB [RFC2863] requires that any
MIB module which is an adjunct of the Interface MIB clarify specific
areas within the Interface MIB. These areas were intentionally left
vague in the Interface MIB to avoid over-constraining the MIB, thereby
precluding management of certain media-types. Section 4 of [RFC2863] enumerates several
areas which a media-specific MIB must clarify. The implementor is
referred to [RFC2863] in order to understand the
general intent of these areas.]]

=== MIB modules required for IMPORTS

[[CREF14: [TEMPLATE TODO]: Citations are not permitted within a MIB module, but any
module mentioned in an IMPORTS clause or document mentioned in a
REFERENCE clause is a Normative reference, and must be cited someplace
within the narrative sections. If there are imported items in the MIB
module, such as Textual Conventions, that are not already cited, they
can be cited in text here. Since relationships to other MIB modules
should be described in the narrative text, this section is typically
used to cite modules from which Textual Conventions are imported. Example: "The following MIB module IMPORTS objects from SNMPv2-SMI [RFC2578], 
SNMPv2-TC [RFC2579],
SNMPv2-CONF [RFC2580], and IF-MIB [RFC2863]."]]

== Definitions
[[CREF15: This section contains the actual MIB module(s).
These MIB modules MUST be written in SMIv2 [RFC2578] [RFC2579]
[RFC2580]. See Section 4 of RFC 4181 for guidelines on SMIv2 usage. 
See Appendix C of RFC 4181 for suggested naming conventions.]]

....
[TEMPLATE TODO]: put your valid MIB module here. 
A list of tools that can help automate the process of 
checking MIB definitions can be found at the OPS 
Area web site.
....

== Security Considerations
[[CREF16: [TEMPLATE TODO] Each internet draft that defines one or more MIB modules MUST
contain a section that discusses security considerations relevant to
those modules. This section MUST be patterned after the latest approved
template (available at the OPS Area web site).   ]]


[[CREF17: [TEMPLATE TODO] if you have any read-write and/or read-create objects, please
describe their specific sensitivity or vulnerability. RFC 2669 has a very good example.   ]]

There are a number of management objects defined in this MIB module
with a MAX-ACCESS clause of read-write and/or read-create. Such objects
may be considered sensitive or vulnerable in some network environments.
The support for SET operations in a non-secure environment without
proper protection can have a negative effect on network operations.
These are the tables and objects and their
sensitivity/vulnerability:

* {blank}

[[CREF18: [TEMPLATE TODO] else if there are no read-write or read-create objects in your MIB module,
use the following boilerplate paragraph.]]

There are no management objects defined in this MIB module that have
a MAX-ACCESS clause of read-write and/or read-create. So, if this MIB
module is implemented correctly, then there is no risk that an intruder
can alter or create any management objects of this MIB module via direct
SNMP SET operations.

[[CREF19: For all MIB modules you must evaluate whether any readable objects
are sensitive or vulnerable (for instance, if they might reveal customer
information or violate personal privacy laws such as those of the
European Union if exposed to unathorized parties).]]

Some of the readable objects in this MIB module (i.e., objects with a
MAX-ACCESS other than not-accessible) may be considered sensitive or
vulnerable in some network environments. It is thus important to control
even GET and/or NOTIFY access to these objects and possibly to even
encrypt the values of these objects when sending them over the network
via SNMP. These are the tables and objects and their
sensitivity/vulnerability: 

* {blank}

* [[CREF20: [TEMPLATE TODO] you should explicitly list by name any readable objects that
are sensitive or vulnerable and the associated security risks should
be spelled out.]]

[[CREF21: [TEMPLATE TODO] The following three boilerplate paragraphs
should not be changed without very good reason. Changes will almost
certainly require justification during IESG review.]]

SNMP versions prior to SNMPv3 did not include adequate security.
Even if the network itself is secure (for example by using IPsec),
there is no control as to who on the secure network is
allowed to access and GET/SET (read/change/create/delete) the objects
in this MIB module.

Implementations SHOULD provide the security features described by the   
SNMPv3 framework (see [RFC3410]), and implementations claiming compliance 
to the SNMPv3 standard MUST include full support for authentication and 
privacy via the User-based Security Model (USM) [RFC3414] with the AES 
cipher algorithm [RFC3826]. Implementations MAY also provide support for
the Transport Security Model (TSM) [RFC5591] in combination with a secure 
transport such as SSH [RFC5592] or TLS/DTLS [RFC6353]. 

Further, deployment of SNMP versions prior to SNMPv3 is NOT
RECOMMENDED. Instead, it is RECOMMENDED to deploy SNMPv3 and to enable
cryptographic security. It is then a customer/operator responsibility to
ensure that the SNMP entity giving access to an instance of this MIB
module is properly configured to give access to the objects only to
those principals (users) that have legitimate rights to indeed GET or
SET (change/create/delete) them.

== IANA Considerations
[[CREF22: [TEMPLATE TODO] In order to comply with IESG policy as set forth in
\http://www.ietf.org/ID-Checklist.html, every Internet-Draft that is
submitted to the IESG for publication MUST contain an IANA
Considerations section. The requirements for this section vary depending
what actions are required of the IANA. See "Guidelines for Writing an IANA 
Considerations Section in RFCs" [RFC2434]. and see RFC4181 section 3.5 for more
information on writing an IANA clause for a MIB module internet draft.]]

Option #1:

....
     The MIB module in this document uses the following IANA-assigned
     OBJECT IDENTIFIER values recorded in the SMI Numbers registry: 
      
     Descriptor        OBJECT IDENTIFIER value
     ----------        -----------------------
     sampleMIB         { mib-2 XXX }
....

Option #2:

Editor's Note (to be removed prior to publication): the IANA is
requested to assign a value for "XXX" under the 'mib-2' subtree and to
record the assignment in the SMI Numbers registry. When the assignment
has been made, the RFC Editor is asked to replace "XXX" (here and in the
MIB module) with the assigned value and to remove this note.

Note well: prior to official assignment by the IANA, an internet
draft MUST use placeholders (such as "XXX" above) rather than actual
numbers. See RFC4181 Section 4.5 for an example of how this is done in
an internet draft MIB module.

Option #3:

This memo includes no request to IANA.

== Contributors

[bibliography]
== Normative References
++++
        <!-- [TEMPLATE TODO] rfc2119, 2578, 2579, and 2580 are required to support MIB
      module boilerplate text. -->

<reference anchor="RFC2119" target="https://www.rfc-editor.org/info/rfc2119">
<front>
<title>
Key words for use in RFCs to Indicate Requirement Levels
</title>
<author initials="S." surname="Bradner" fullname="S. Bradner">
<organization/>
</author>
<date year="1997" month="March"/>
<abstract>
<t>
In many standards track documents several words are used to signify the requirements in the specification. These words are often capitalized. This document defines these words as they should be interpreted in IETF documents. This document specifies an Internet Best Current Practices for the Internet Community, and requests discussion and suggestions for improvements.
</t>
</abstract>
</front>
<seriesInfo name="BCP" value="14"/>
<seriesInfo name="RFC" value="2119"/>
<seriesInfo name="DOI" value="10.17487/RFC2119"/>
</reference>

 <reference anchor="RFC2578" target="https://www.rfc-editor.org/info/rfc2578">
<front>
<title>
Structure of Management Information Version 2 (SMIv2)
</title>
<author initials="K." surname="McCloghrie" fullname="K. McCloghrie" role="editor">
<organization/>
</author>
<author initials="D." surname="Perkins" fullname="D. Perkins" role="editor">
<organization/>
</author>
<author initials="J." surname="Schoenwaelder" fullname="J. Schoenwaelder" role="editor">
<organization/>
</author>
<date year="1999" month="April"/>
<abstract>
<t>
It is the purpose of this document, the Structure of Management Information Version 2 (SMIv2), to define that adapted subset, and to assign a set of associated administrative values. [STANDARDS-TRACK]
</t>
</abstract>
</front>
<seriesInfo name="STD" value="58"/>
<seriesInfo name="RFC" value="2578"/>
<seriesInfo name="DOI" value="10.17487/RFC2578"/>
</reference>

<reference anchor="RFC2579" target="https://www.rfc-editor.org/info/rfc2579">
<front>
<title>Textual Conventions for SMIv2</title>
<author initials="K." surname="McCloghrie" fullname="K. McCloghrie" role="editor">
<organization/>
</author>
<author initials="D." surname="Perkins" fullname="D. Perkins" role="editor">
<organization/>
</author>
<author initials="J." surname="Schoenwaelder" fullname="J. Schoenwaelder" role="editor">
<organization/>
</author>
<date year="1999" month="April"/>
<abstract>
<t>
It is the purpose of this document to define the initial set of textual conventions available to all MIB modules. [STANDARDS-TRACK]
</t>
</abstract>
</front>
<seriesInfo name="STD" value="58"/>
<seriesInfo name="RFC" value="2579"/>
<seriesInfo name="DOI" value="10.17487/RFC2579"/>
</reference>

<reference anchor="RFC2580" target="https://www.rfc-editor.org/info/rfc2580">
<front>
<title>Conformance Statements for SMIv2</title>
<author initials="K." surname="McCloghrie" fullname="K. McCloghrie" role="editor">
<organization/>
</author>
<author initials="D." surname="Perkins" fullname="D. Perkins" role="editor">
<organization/>
</author>
<author initials="J." surname="Schoenwaelder" fullname="J. Schoenwaelder" role="editor">
<organization/>
</author>
<date year="1999" month="April"/>
<abstract>
<t>
Collections of related objects are defined in MIB modules. It may be useful to define the acceptable lower-bounds of implementation, along with the actual level of implementation achieved. It is the purpose of this document to define the notation used for these purposes. [STANDARDS-TRACK]
</t>
</abstract>
</front>
<seriesInfo name="STD" value="58"/>
<seriesInfo name="RFC" value="2580"/>
<seriesInfo name="DOI" value="10.17487/RFC2580"/>
</reference>
++++

[bibliography]
== Informative References
++++

<!--  RFC3410 is required to support the boilerplate text.-->
<reference anchor="RFC2223" target="https://www.rfc-editor.org/info/rfc2223">
<front>
<title>Instructions to RFC Authors</title>
<author initials="J." surname="Postel" fullname="J. Postel">
<organization/>
</author>
<author initials="J." surname="Reynolds" fullname="J. Reynolds">
<organization/>
</author>
<date year="1997" month="October"/>
<abstract>
<t>
This Request for Comments (RFC) provides information about the preparation of RFCs, and certain policies relating to the publication of RFCs. This memo provides information for the Internet community. This memo does not specify an Internet standard of any kind.
</t>
</abstract>
</front>
<seriesInfo name="RFC" value="2223"/>
<seriesInfo name="DOI" value="10.17487/RFC2223"/>
</reference>

<reference anchor="RFC3410" target="https://www.rfc-editor.org/info/rfc3410">
<front>
<title>
Introduction and Applicability Statements for Internet-Standard Management Framework
</title>
<author initials="J." surname="Case" fullname="J. Case">
<organization/>
</author>
<author initials="R." surname="Mundy" fullname="R. Mundy">
<organization/>
</author>
<author initials="D." surname="Partain" fullname="D. Partain">
<organization/>
</author>
<author initials="B." surname="Stewart" fullname="B. Stewart">
<organization/>
</author>
<date year="2002" month="December"/>
<abstract>
<t>
The purpose of this document is to provide an overview of the third version of the Internet-Standard Management Framework, termed the SNMP version 3 Framework (SNMPv3). This Framework is derived from and builds upon both the original Internet-Standard Management Framework (SNMPv1) and the second Internet-Standard Management Framework (SNMPv2). The architecture is designed to be modular to allow the evolution of the Framework over time. The document explains why using SNMPv3 instead of SNMPv1 or SNMPv2 is strongly recommended. The document also recommends that RFCs 1157, 1441, 1901, 1909 and 1910 be retired by moving them to Historic status. This document obsoletes RFC 2570. This memo provides information for the Internet community.
</t>
</abstract>
</front>
<seriesInfo name="RFC" value="3410"/>
<seriesInfo name="DOI" value="10.17487/RFC3410"/>
</reference>

<reference anchor="RFC2629" target="https://www.rfc-editor.org/info/rfc2629">
<front>
<title>Writing I-Ds and RFCs using XML</title>
<author initials="M." surname="Rose" fullname="M. Rose">
<organization/>
</author>
<date year="1999" month="June"/>
<abstract>
<t>
This memo presents a technique for using XML (Extensible Markup Language) as a source format for documents in the Internet-Drafts (I-Ds) and Request for Comments (RFC) series. This memo provides information for the Internet community.
</t>
</abstract>
</front>
<seriesInfo name="RFC" value="2629"/>
<seriesInfo name="DOI" value="10.17487/RFC2629"/>
</reference>

<reference anchor="RFC4181" target="https://www.rfc-editor.org/info/rfc4181">
<front>
<title>
Guidelines for Authors and Reviewers of MIB Documents
</title>
<author initials="C." surname="Heard" fullname="C. Heard" role="editor">
<organization/>
</author>
<date year="2005" month="September"/>
<abstract>
<t>
This memo provides guidelines for authors and reviewers of IETF standards-track specifications containing MIB modules. Applicable portions may be used as a basis for reviews of other MIB documents. This document specifies an Internet Best Current Practices for the Internet Community, and requests discussion and suggestions for improvements.
</t>
</abstract>
</front>
<seriesInfo name="BCP" value="111"/>
<seriesInfo name="RFC" value="4181"/>
<seriesInfo name="DOI" value="10.17487/RFC4181"/>
</reference>
++++

[bibliography]
== URL References
++++
<reference anchor="idguidelines">
	<front>
		<title>http://www.ietf.org/ietf/1id-guidelines.txt</title>
		<author>
			<organization>IETF Internet Drafts editor</organization>
		</author>
		<date year=""></date>
	</front>
</reference>
<reference anchor="idnits">
	<front>
		<title>http://www.ietf.org/ID-Checklist.html</title>
		<author>
			<organization>IETF Internet Drafts editor</organization>
		</author>
		<date year=""></date>
	</front>
</reference>
<reference anchor="xml2rfc">
	<front>
		<title>http://xml.resource.org</title>
		<author>
			<organization>XML2RFC tools and documentation</organization>
		</author>
		<date year=""></date>
	</front>
</reference>								
<reference anchor="ops">
	<front>
		<title>http://www.ops.ietf.org</title>
		<author>
			<organization>the IETF OPS Area</organization>
		</author>
		<date year=""></date>
	</front>
</reference>		
<reference anchor="ietf">
	<front>
		<title>http://tools.ietf.org</title>
		<author>
			<organization>IETF Tools Team</organization>
		</author>
		<date year=""></date>
	</front>
</reference>						
++++

[[appendix]]
== Change Log
Note to RFC Editor: if this document does not obsolete an existing RFC, 
please remove this appendix before publication as an RFC.

== Open Issues
Note to RFC Editor: please remove this appendix before publication as an RFC.
