= The Security Flag in the IPv4 Header
Steven M. Bellovin <bellovin@acm.org>
:doctype: internet-draft
:abbrev: The Security Flag in the IPv4 Header
:status: info
:name: rfc-3514
:ipr: trust200902
:area: Internet
:workgroup: Network Working Group
:revdate: 2003-04-01T00:00:00Z
:forename_initials: S.
:organization: AT&T Labs Research
:phone: +1 973-360-8656
:street: 180 Park Avenue
:city: Florham Park
:code: NJ 07932
:smart-quotes: false

[abstract]
Firewalls, packet filters, intrusion detection systems, and the like
often have difficulty distinguishing between packets that have
malicious intent and those that are merely unusual.  We define a
security flag in the IPv4 header as a means of distinguishing the two
cases.

[[introduction]]
== Introduction

Firewalls <<CBR03>>, packet filters, intrusion detection systems, and
the like often have difficulty distinguishing between packets that
have malicious intent and those that are merely unusual.  The problem
is that making such determinations is hard.  To solve this problem,
we define a security flag, known as the "evil" bit, in the IPv4
<<RFC0791>> header.  Benign packets have this bit set to 0; those that
are used for an attack will have the bit set to 1.

[[terminology]]
=== Terminology

The keywords **MUST**, **MUST NOT**, **REQUIRED**, **SHALL**, **SHALL NOT**, **SHOULD**,
**SHOULD NOT**, **RECOMMENDED**, **MAY**, and **OPTIONAL**, when they appear in this
document, are to be interpreted as described in <<RFC2119>>.

[[syntax]]
== Syntax

The high-order bit of the IP fragment offset field is the only unused
bit in the IP header.  Accordingly, the selection of the bit position
is not left to IANA.

The bit field is laid out as follows:

....
     0
    +-+
    |E|
    +-+
....

Currently-assigned values are defined as follows:

0x0:: 
+
If the bit is set to 0, the packet has no evil intent.  Hosts,
    network elements, etc., **SHOULD** assume that the packet is
    harmless, and **SHOULD NOT** take any defensive measures.  (We note
    that this part of the spec is already implemented by many common
    desktop operating systems.)

0x1:: 
+
If the bit is set to 1, the packet has evil intent.  Secure
    systems **SHOULD** try to defend themselves against such packets.
    Insecure systems **MAY** chose to crash, be penetrated, etc.

[[setting-the-evil-bit]]
== Setting the Evil Bit

There are a number of ways in which the evil bit may be set.  Attack
applications may use a suitable API to request that it be set.
Systems that do not have other mechanisms **MUST** provide such an API;
attack programs **MUST** use it.

Multi-level insecure operating systems may have special levels for
attack programs; the evil bit **MUST** be set by default on packets
emanating from programs running at such levels.  However, the system
*MAY* provide an API to allow it to be cleared for non-malicious
activity by users who normally engage in attack behavior.

Fragments that by themselves are dangerous **MUST** have the evil bit
set.  If a packet with the evil bit set is fragmented by an
intermediate router and the fragments themselves are not dangerous,
the evil bit **MUST** be cleared in the fragments, and **MUST** be turned
back on in the reassembled packet.

Intermediate systems are sometimes used to launder attack
connections.  Packets to such systems that are intended to be relayed
to a target SHOULD have the evil bit set.

Some applications hand-craft their own packets.  If these packets are
part of an attack, the application **MUST** set the evil bit by itself.

In networks protected by firewalls, it is axiomatic that all
attackers are on the outside of the firewall.  Therefore, hosts
inside the firewall **MUST NOT** set the evil bit on any packets.

Because NAT <<RFC3022>> boxes modify packets, they **SHOULD** set the evil
bit on such packets.  "Transparent" http and email proxies **SHOULD** set
the evil bit on their reply packets to the innocent client host.

Some hosts scan other hosts in a fashion that can alert intrusion
detection systems.  If the scanning is part of a benign research
project, the evil bit **MUST NOT** be set.  If the scanning per se is
innocent, but the ultimate intent is evil and the destination site
has such an intrusion detection system, the evil bit **SHOULD** be set.

[[processing-of-the-evil-bit]]
== Processing of the Evil Bit

Devices such as firewalls **MUST** drop all inbound packets that have the
evil bit set.  Packets with the evil bit off **MUST NOT** be dropped.
Dropped packets **SHOULD** be noted in the appropriate MIB variable.

Intrusion detection systems (IDSs) have a harder problem.  Because of
their known propensity for false negatives and false positives, IDSs
**MUST** apply a probabilistic correction factor when evaluating the evil
bit.  If the evil bit is set, a suitable random number generator
<<RFC1750>> must be consulted to determine if the attempt should be
logged.  Similarly, if the bit is off, another random number
generator must be consulted to determine if it should be logged
despite the setting.

The default probabilities for these tests depends on the type of IDS.
Thus, a signature-based IDS would have a low false positive value but
a high false negative value.  A suitable administrative interface
**MUST** be provided to permit operators to reset these values.

Routers that are not intended as as security devices **SHOULD NOT**
examine this bit. This will allow them to pass packets at higher
speeds.

As outlined earlier, host processing of evil packets is operating-
system dependent; however, all hosts **MUST** react appropriately
according to their nature.

[[related-work]]
== Related Work

Although this document only defines the IPv4 evil bit, there are
complementary mechanisms for other forms of evil.  We sketch some of
those here.

For IPv6 <<RFC2460>>, evilness is conveyed by two options.  The first,
a hop-by-hop option, is used for packets that damage the network,
such as DDoS packets.  The second, an end-to-end option, is for
packets intended to damage destination hosts.  In either case, the
option contains a 128-bit strength indicator, which says how evil the
packet is, and a 128-bit type code that describes the particular type
of attack intended.

Some link layers, notably those based on optical switching, may
bypass routers (and hence firewalls) entirely.  Accordingly, some
link-layer scheme **MUST** be used to denote evil.  This may involve evil
lambdas, evil polarizations, etc.

DDoS attack packets are denoted by a special diffserv code point.

An application/evil MIME type is defined for Web- or email-carried
mischief.  Other MIME types can be embedded inside of evil sections;
this permit easy encoding of word processing documents with macro
viruses, etc.

[[iana-considerations]]
== IANA Considerations

This document defines the behavior of security elements for the 0x0
and 0x1 values of this bit.  Behavior for other values of the bit may
be defined only by IETF consensus <<RFC2434>>.

[[security-considerations]]
== Security Considerations

Correct functioning of security mechanisms depend critically on the
evil bit being set properly.  If faulty components do not set the
evil bit to 1 when appropriate, firewalls will not be able to do
their jobs properly.  Similarly, if the bit is set to 1 when it
shouldn't be, a denial of service condition may occur.


[bibliography]
== Normative References
++++

<reference anchor="RFC0791" target="https://www.rfc-editor.org/info/rfc791">
<front>
<title>Internet Protocol</title>
<author initials="J." surname="Postel" fullname="J. Postel">
<organization/>
</author>
<date year="1981" month="September"/>
</front>
<seriesInfo name="STD" value="5"/>
<seriesInfo name="RFC" value="791"/>
<seriesInfo name="DOI" value="10.17487/RFC0791"/>
</reference>

<reference anchor="RFC1750" target="https://www.rfc-editor.org/info/rfc1750">
<front>
<title>Randomness Recommendations for Security</title>
<author initials="D." surname="Eastlake 3rd" fullname="D. Eastlake 3rd">
<organization/>
</author>
<author initials="S." surname="Crocker" fullname="S. Crocker">
<organization/>
</author>
<author initials="J." surname="Schiller" fullname="J. Schiller">
<organization/>
</author>
<date year="1994" month="December"/>
<abstract>
<t>
Choosing random quantities to foil a resourceful and motivated adversary is surprisingly difficult. This paper points out many pitfalls in using traditional pseudo-random number generation techniques for choosing such quantities. It recommends the use of truly random hardware techniques and shows that the existing hardware on many systems can be used for this purpose. This memo provides information for the Internet community. This memo does not specify an Internet standard of any kind.
</t>
</abstract>
</front>
<seriesInfo name="RFC" value="1750"/>
<seriesInfo name="DOI" value="10.17487/RFC1750"/>
</reference>

<reference anchor="RFC2119" target="https://www.rfc-editor.org/info/rfc2119">
<front>
<title>
Key words for use in RFCs to Indicate Requirement Levels
</title>
<author initials="S." surname="Bradner" fullname="S. Bradner">
<organization/>
</author>
<date year="1997" month="March"/>
<abstract>
<t>
In many standards track documents several words are used to signify the requirements in the specification. These words are often capitalized. This document defines these words as they should be interpreted in IETF documents. This document specifies an Internet Best Current Practices for the Internet Community, and requests discussion and suggestions for improvements.
</t>
</abstract>
</front>
<seriesInfo name="BCP" value="14"/>
<seriesInfo name="RFC" value="2119"/>
<seriesInfo name="DOI" value="10.17487/RFC2119"/>
</reference>

<reference anchor="RFC2434" target="https://www.rfc-editor.org/info/rfc2434">
<front>
<title>
Guidelines for Writing an IANA Considerations Section in RFCs
</title>
<author initials="T." surname="Narten" fullname="T. Narten">
<organization/>
</author>
<author initials="H." surname="Alvestrand" fullname="H. Alvestrand">
<organization/>
</author>
<date year="1998" month="October"/>
<abstract>
<t>
This document discusses issues that should be considered in formulating a policy for assigning values to a name space and provides guidelines to document authors on the specific text that must be included in documents that place demands on the IANA. This document specifies an Internet Best Current Practices for the Internet Community, and requests discussion and suggestions for improvements.
</t>
</abstract>
</front>
<seriesInfo name="RFC" value="2434"/>
<seriesInfo name="DOI" value="10.17487/RFC2434"/>
</reference>

<reference anchor="RFC2460" target="https://www.rfc-editor.org/info/rfc2460">
<front>
<title>Internet Protocol, Version 6 (IPv6) Specification</title>
<author initials="S." surname="Deering" fullname="S. Deering">
<organization/>
</author>
<author initials="R." surname="Hinden" fullname="R. Hinden">
<organization/>
</author>
<date year="1998" month="December"/>
<abstract>
<t>
This document specifies version 6 of the Internet Protocol (IPv6), also sometimes referred to as IP Next Generation or IPng. [STANDARDS-TRACK]
</t>
</abstract>
</front>
<seriesInfo name="RFC" value="2460"/>
<seriesInfo name="DOI" value="10.17487/RFC2460"/>
</reference>

<reference anchor="RFC3022" target="https://www.rfc-editor.org/info/rfc3022">
<front>
<title>
Traditional IP Network Address Translator (Traditional NAT)
</title>
<author initials="P." surname="Srisuresh" fullname="P. Srisuresh">
<organization/>
</author>
<author initials="K." surname="Egevang" fullname="K. Egevang">
<organization/>
</author>
<date year="2001" month="January"/>
<abstract>
<t>
The NAT operation described in this document extends address translation introduced in RFC 1631 and includes a new type of network address and TCP/UDP port translation. In addition, this document corrects the Checksum adjustment algorithm published in RFC 1631 and attempts to discuss NAT operation and limitations in detail. This memo provides information for the Internet community.
</t>
</abstract>
</front>
<seriesInfo name="RFC" value="3022"/>
<seriesInfo name="DOI" value="10.17487/RFC3022"/>
</reference>

<reference anchor='CBR03' target=''>
 <front>
 <title>Firewalls and Internet Security: Repelling the Wily Hacker, Second Edition</title>
  <author initials='W.R.' surname='Cheswick' fullname='W.R. Cheswick'></author>
  <author initials='S.M.' surname='Bellovin' fullname='S.M. Bellovin'></author>
  <author initials='A.D.' surname='Rubin' fullname='A.D. Rubin'></author>
  <date year='2003' />
 </front>
 <seriesInfo name="Addison-Wesley" value='' />
 </reference>
++++
